# 9 WorkFlow Analista Jr

### 9.1 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
<br>El Analista Jr corre sus scripts en la virtual manchine **desktop-jr** que tiene estas características


*   Normal, paga tarifa completa, nunca es apagada por Google
*   reside en el datacenter de Toronto, Canada
*   64 GB de memoria RAM
*   8 vCPU


En Analista Jr **no** puede utilizar Google Colab porque los 12 GB de dichas maquinas virtuales no son suficientes para el tamaño del dataset que está utilizando.

## 9.3  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Wed Sep 09 19:16:52 2026"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671184 35.9 1479548    79.1 1479548  79.1
Vcells 1242574  9.5 8388608    64.0 1978697  15.1

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:base’:

    %notin%


Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
# Configuración general de la corrida
PARAM <- list()

# Cambiar estos valores para cada escenario
PARAM$experimento <- 9140
PARAM$nombre_escenario <- "M2_sin_febrero_marzo_2020"
PARAM$meses_excluidos <- c(
  202002,
  202003
)

# Semillas definidas explícitamente
PARAM$semillas <- c(
  700001L,
  690506L,
  804528L,
  613037L,
  648983L,
  365305L,
  163687L
)

PARAM$cantidad_semillas <- length(PARAM$semillas)
PARAM$semilla_primigenia <- PARAM$semillas[1]

PARAM$dataset <- "analistajr_competencia_2026.csv.gz"

# TRUE: genera archivos y los sube.
# FALSE: solamente genera los archivos.
PARAM$subir_kaggle <- TRUE

# Validaciones
stopifnot(PARAM$cantidad_semillas >= 1L)
stopifnot(!anyDuplicated(PARAM$semillas))
stopifnot(all(PARAM$semillas > 0L))

# Muestra las semillas que utilizará
PARAM$semillas

[1] 700001 690506 804528 613037 648983 365305 163687

#### Carpeta del Experimento

In [5]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("WF", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

### 9.3.1   Preprocesamiento del dataset

#### 9.3.1.1  DT incorporar dataset

In [6]:
# lectura del dataset
dataset <- fread(paste0("/content/datasets/", PARAM$dataset))

#### 9.3.1.2  CA  Catastrophe Analysis
Se intentan reparar las variables que para un mes están con todos los valores en cero.

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

In [7]:
if( !require("mice")) install.packages("mice", repos = "http://cran.us.r-project.org")
require("mice")

Loading required package: mice


Attaching package: ‘mice’


The following object is masked from ‘package:stats’:

    filter


The following objects are masked from ‘package:base’:

    cbind, rbind

In [8]:
# Escrito por alumnos de  Universidad Austral  Rosario

Corregir_MICE <- function(pcampo, pmeses) {

  meth <- rep("", ncol(dataset))
  names(meth) <- colnames(dataset)
  meth[names(meth) == pcampo] <- "sample"

  # llamada a mice  !
  imputacion <- mice(dataset,
    method = meth,
    maxit = 5,
    m = 1,
    seed = 7)

  tbl <- mice::complete(dataset)

  dataset[, paste0(pcampo) := ifelse(foto_mes %in% pmeses, tbl[, get(pcampo)], get(pcampo))]

}

In [9]:
Corregir_interpolar <- function(pcampo, pmeses) {

  tbl <- dataset[, list(
    "v1" = shift(get(pcampo), 1, type = "lag"),
    "v2" = shift(get(pcampo), 1, type = "lead")
  ),
  by = eval(envg$PARAM$dataset_metadata$entity_id)
  ]

  tbl[, paste0(envg$PARAM$dataset_metadata$entity_id) := NULL]
  tbl[, promedio := rowMeans(tbl, na.rm = TRUE)]

  dataset[
    ,
    paste0(pcampo) := ifelse(!(foto_mes %in% pmeses),
      get(pcampo),
      tbl$promedio
    )
  ]
}

In [10]:
AsignarNA_campomeses <- function(pcampo, pmeses) {

  if( pcampo %in% colnames( dataset ) ) {

    dataset[ foto_mes %in% pmeses, paste0(pcampo) := NA ]
  }
}

In [11]:

Corregir_atributo <- function(pcampo, pmeses, pmetodo)
{
  # si el campo no existe en el dataset, Afuera !
  if( !(pcampo %in% colnames( dataset )) )
    return( 1 )

  # llamo a la funcion especializada que corresponde
  switch( pmetodo,
    "MachineLearning"     = AsignarNA_campomeses(pcampo, pmeses),
    "EstadisticaClasica"  = Corregir_interpolar(pcampo, pmeses),
    "MICE"                = Corregir_MICE(pcampo, pmeses),
  )

  return( 0 )
}

In [12]:

Corregir_Rotas <- function(dataset, pmetodo) {
  gc(verbose= FALSE)
  cat( "inicio Corregir_Rotas()\n")
  # acomodo los errores del dataset

  Corregir_atributo("active_quarter", c(202006), pmetodo) # 1
  Corregir_atributo("internet", c(202006), pmetodo) # 2

  Corregir_atributo("mrentabilidad", c(201905, 201910, 202006), pmetodo) # 3
  Corregir_atributo("mrentabilidad_annual", c(201905, 201910, 202006), pmetodo) # 4

  Corregir_atributo("mcomisiones", c(201905, 201910, 202006), pmetodo) # 5

  Corregir_atributo("mactivos_margen", c(201905, 201910, 202006), pmetodo) # 6
  Corregir_atributo("mpasivos_margen", c(201905, 201910, 202006), pmetodo) # 7

  Corregir_atributo("mcuentas_saldo", c(202006), pmetodo) # 8

  Corregir_atributo("ctarjeta_debito_transacciones", c(202006), pmetodo) # 9

  Corregir_atributo("mautoservicio", c(202006), pmetodo) # 10

  Corregir_atributo("ctarjeta_visa_transacciones", c(202006), pmetodo) # 11
  Corregir_atributo("mtarjeta_visa_consumo", c(202006), pmetodo) # 12

  Corregir_atributo("ctarjeta_master_transacciones", c(202006), pmetodo) # 13
  Corregir_atributo("mtarjeta_master_consumo", c(202006), pmetodo) # 14

  Corregir_atributo("ctarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 15
  Corregir_atributo("mttarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 16

  Corregir_atributo("ccajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 17

  Corregir_atributo("mcajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 18

  Corregir_atributo("ctarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 19

  Corregir_atributo("mtarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 20

  Corregir_atributo("ctarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 21

  Corregir_atributo("mtarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 22

  Corregir_atributo("ccomisiones_otras", c(201905, 201910, 202006), pmetodo) # 23
  Corregir_atributo("mcomisiones_otras", c(201905, 201910, 202006), pmetodo) # 24

  Corregir_atributo("cextraccion_autoservicio", c(202006), pmetodo) # 25
  Corregir_atributo("mextraccion_autoservicio", c(202006), pmetodo) # 26

  Corregir_atributo("ccheques_depositados", c(202006), pmetodo) # 27
  Corregir_atributo("mcheques_depositados", c(202006), pmetodo) # 28
  Corregir_atributo("ccheques_emitidos", c(202006), pmetodo) # 29
  Corregir_atributo("mcheques_emitidos", c(202006), pmetodo) # 30
  Corregir_atributo("ccheques_depositados_rechazados", c(202006), pmetodo) # 31
  Corregir_atributo("mcheques_depositados_rechazados", c(202006), pmetodo) # 32
  Corregir_atributo("ccheques_emitidos_rechazados", c(202006), pmetodo) # 33
  Corregir_atributo("mcheques_emitidos_rechazados", c(202006), pmetodo) # 34

  Corregir_atributo("tcallcenter", c(202006), pmetodo) # 35
  Corregir_atributo("ccallcenter_transacciones", c(202006), pmetodo) # 36

  Corregir_atributo("thomebanking", c(202006), pmetodo) # 37
  Corregir_atributo("chomebanking_transacciones", c(201910, 202006), pmetodo) # 38

  Corregir_atributo("ccajas_transacciones", c(202006), pmetodo) # 39
  Corregir_atributo("ccajas_consultas", c(202006), pmetodo) # 40

  Corregir_atributo("ccajas_depositos", c(202006, 202105), pmetodo) # 41

  Corregir_atributo("ccajas_extracciones", c(202006), pmetodo) # 41
  Corregir_atributo("ccajas_otras", c(202006), pmetodo) # 43

  Corregir_atributo("catm_trx", c(202006), pmetodo) # 44
  Corregir_atributo("matm", c(202006), pmetodo) # 45
  Corregir_atributo("catm_trx_other", c(202006), pmetodo) # 46
  Corregir_atributo("matm_other", c(202006), pmetodo) # 47

  cat( "fin Corregir_rotas()\n")
}

In [13]:
# resuelvo el Catastrophe Analysis

setorder( dataset, numero_de_cliente, foto_mes )

PARAM$CA$metodo= "MachineLearning"

if( PARAM$CA$metodo %in% c("MachineLearning", "EstadisticaClasica", "MICE") )
  Corregir_Rotas(dataset, PARAM$CA$metodo)

inicio Corregir_Rotas()
fin Corregir_rotas()

#### 9.3.1.3  DR  Data Drifting
Se intenta corregir el data drifting, ajustando por algunos indices financieros

In [14]:
# meses que me interesan para el ajuste de variables monetarias
vfoto_mes <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107, 202108, 202109
)

In [15]:
# los valores que siguen fueron calculados por alumnos

# momento 1.0  31-dic-2020 a las 23:59
vIPC <- c(
  1.9903030878, 1.9174403544, 1.8296186587,
  1.7728862972, 1.7212488323, 1.6776304408,
  1.6431248196, 1.5814483345, 1.4947526791,
  1.4484037589, 1.3913580777, 1.3404220402,
  1.3154288912, 1.2921698342, 1.2472681797,
  1.2300475145, 1.2118694724, 1.1881073259,
  1.1693969743, 1.1375456949, 1.1065619600,
  1.0681100000, 1.0370000000, 1.0000000000,
  0.9680542110, 0.9344152616, 0.8882274350,
  0.8532444140, 0.8251880213, 0.8003763543,
  0.7763107219, 0.7566381305, 0.7289384687
)

vdolar_blue <- c(
   39.045455,  38.402500,  41.639474,
   44.274737,  46.095455,  45.063333,
   43.983333,  54.842857,  61.059524,
   65.545455,  66.750000,  72.368421,
   77.477273,  78.191667,  82.434211,
  101.087500, 126.236842, 125.857143,
  130.782609, 133.400000, 137.954545,
  170.619048, 160.400000, 153.052632,
  157.900000, 149.380952, 143.615385,
  146.250000, 153.550000, 162.000000,
  178.478261, 180.878788, 184.357143
)

vdolar_oficial <- c(
   38.430000,  39.428000,  42.542105,
   44.354211,  46.088636,  44.955000,
   43.751429,  54.650476,  58.790000,
   61.403182,  63.012632,  63.011579,
   62.983636,  63.580556,  65.200000,
   67.872000,  70.047895,  72.520952,
   75.324286,  77.488500,  79.430909,
   83.134762,  85.484737,  88.181667,
   91.474000,  93.997778,  96.635909,
   98.526000,  99.613158, 100.619048,
  101.619048, 102.569048, 103.781818
)

vUVA <- c(
  2.001408838932958,  1.950325472789153,  1.89323032351521,
  1.8247220405493787, 1.746027787673673,  1.6871348409529485,
  1.6361678865622313, 1.5927529755859773, 1.5549162794128493,
  1.4949100586391746, 1.4197729500774545, 1.3678188186372326,
  1.3136508617223726, 1.2690535173062818, 1.2381595983200178,
  1.211656735577568,  1.1770808941405335, 1.1570338657445522,
  1.1388769475653255, 1.1156993751209352, 1.093638313080772,
  1.0657171590878205, 1.0362173587708712, 1.0,
  0.9669867858358365, 0.9323750098728378, 0.8958202912590305,
  0.8631993702994263, 0.8253893405524657, 0.7928918905364516,
  0.7666323845128089, 0.7428976357662823, 0.721615762047849
)

In [16]:
tb_indices <- as.data.table( list(
  "IPC" = vIPC,
  "dolar_blue" = vdolar_blue,
  "dolar_oficial" = vdolar_oficial,
  "UVA" = vUVA
  )
)

tb_indices[[ 'foto_mes' ]] <- vfoto_mes

tb_indices

   IPC       dolar_blue dolar_oficial UVA       foto_mes
1  1.9903031  39.04545   38.43000     2.0014088 201901
2  1.9174404  38.40250   39.42800     1.9503255 201902
3  1.8296187  41.63947   42.54210     1.8932303 201903
4  1.7728863  44.27474   44.35421     1.8247220 201904
5  1.7212488  46.09546   46.08864     1.7460278 201905
6  1.6776304  45.06333   44.95500     1.6871348 201906
7  1.6431248  43.98333   43.75143     1.6361679 201907
8  1.5814483  54.84286   54.65048     1.5927530 201908
9  1.4947527  61.05952   58.79000     1.5549163 201909
10 1.4484038  65.54546   61.40318     1.4949101 201910
11 1.3913581  66.75000   63.01263     1.4197730 201911
12 1.3404220  72.36842   63.01158     1.3678188 201912
13 1.3154289  77.47727   62.98364     1.3136509 202001
14 1.2921698  78.19167   63.58056     1.2690535 202002
15 1.2472682  82.43421   65.20000     1.2381596 202003
16 1.2300475 101.08750   67.87200     1.2116567 202004
17 1.2118695 126.23684   70.04789     1.1770809 202005
18 1.1881073 125.85714   72.52095     1.1570339 202006
19 1.1693970 130.78261   75.32429     1.1388769 202007
20 1.1375457 133.40000   77.48850     1.1156994 202008
21 1.1065620 137.95454   79.43091     1.0936383 202009
22 1.0681100 170.61905   83.13476     1.0657172 202010
23 1.0370000 160.40000   85.48474     1.0362174 202011
24 1.0000000 153.05263   88.18167     1.0000000 202012
25 0.9680542 157.90000   91.47400     0.9669868 202101
26 0.9344153 149.38095   93.99778     0.9323750 202102
27 0.8882274 143.61539   96.63591     0.8958203 202103
28 0.8532444 146.25000   98.52600     0.8631994 202104
29 0.8251880 153.55000   99.61316     0.8253893 202105
30 0.8003764 162.00000  100.61905     0.7928919 202106
31 0.7763107 178.47826  101.61905     0.7666324 202107
32 0.7566381 180.87879  102.56905     0.7428976 202108
33 0.7289385 184.35714  103.78182     0.7216158 202109

In [17]:
drift_UVA <- function(campos_monetarios) {
  cat( "inicio drift_UVA()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.UVA,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_UVA()\n")
}

In [18]:
drift_dolar_oficial <- function(campos_monetarios) {
  cat( "inicio drift_dolar_oficial()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_oficial,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_oficial()\n")
}

In [19]:
drift_dolar_blue <- function(campos_monetarios) {
  cat( "inicio drift_dolar_blue()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_blue,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_blue()\n")
}

In [20]:
drift_deflacion <- function(campos_monetarios) {
  cat( "inicio drift_deflacion()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.IPC,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_deflacion()\n")
}

In [21]:
drift_rank_simple <- function(campos_drift) {

  cat( "inicio drift_rank_simple()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_rank") :=
      (frank(get(campo), ties.method = "random") - 1) / (.N - 1), by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat( "fin drift_rank_simple()\n")
}

In [22]:
# El cero se transforma en cero
# los positivos se rankean por su lado
# los negativos se rankean por su lado

drift_rank_cero_fijo <- function(campos_drift) {

  cat( "inicio drift_rank_cero_fijo()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[get(campo) == 0, paste0(campo, "_rank") := 0]
    dataset[get(campo) > 0, paste0(campo, "_rank") :=
      frank(get(campo), ties.method = "random") / .N, by = list(foto_mes)]

    dataset[get(campo) < 0, paste0(campo, "_rank") :=
      -frank(-get(campo), ties.method = "random") / .N, by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat("\n")
  cat( "fin drift_rank_cero_fijo()\n")
}

In [23]:
drift_estandarizar <- function(campos_drift) {

  cat( "inicio drift_estandarizar()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_normal") :=
      (get(campo) -mean(campo, na.rm=TRUE)) / sd(get(campo), na.rm=TRUE),
      by = list(foto_mes)]

    dataset[, (campo) := NULL]
  }
  cat( "fin drift_estandarizar()\n")
}

In [24]:
# por como armé los nombres de campos,
#  estos son los campos que expresan variables monetarias
campos_monetarios <- colnames(dataset)
campos_monetarios <- campos_monetarios[campos_monetarios %like%
  "^(m|Visa_m|Master_m|vm_m)"]

campos_monetarios

 [1] "mrentabilidad"                      "mrentabilidad_annual"
 [3] "mcomisiones"                        "mactivos_margen"
 [5] "mpasivos_margen"                    "mcuenta_corriente"
 [7] "mcaja_ahorro"                       "mcuentas_saldo"
 [9] "mtarjeta_visa_consumo"              "mtarjeta_master_consumo"
[11] "mprestamos_personales"              "mpayroll"
[13] "mttarjeta_visa_debitos_automaticos" "mcomisiones_mantenimiento"
[15] "mtransferencias_recibidas"          "Master_mfinanciacion_limite"
[17] "Master_msaldototal"                 "Master_mlimitecompra"
[19] "Master_mconsumototal"               "Master_mpagominimo"
[21] "Visa_mfinanciacion_limite"          "Visa_msaldototal"
[23] "Visa_mlimitecompra"                 "Visa_mconsumototal"
[25] "Visa_mpagominimo"

In [25]:
# ejecuto el Data Drifting
setorder( dataset, numero_de_cliente, foto_mes )


PARAM$DR$metodo <- "deflacion"

switch(PARAM$DR$metodo,
  "ninguno"        = cat("No hay correccion del data drifting"),
  "rank_simple"    = drift_rank_simple(campos_monetarios),
  "rank_cero_fijo" = drift_rank_cero_fijo(campos_monetarios),
  "deflacion"      = drift_deflacion(campos_monetarios),
  "dolar_blue"     = drift_dolarblue(campos_monetarios),
  "dolar_oficial"  = drift_dolaroficial(campos_monetarios),
  "UVA"            = drift_UVA(campos_monetarios),
  "estandarizar"   = drift_estandarizar(campos_monetarios)
)

inicio drift_deflacion()
fin drift_deflacion()

In [26]:
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"

In [27]:
# se intenta corregir el data drifting utilizando algunos indices financieros

#### 9.3.1.3  FE_intra_manual Feature Engineering intra-mes

Agrego campos nuevos dentro del mismo mes, SIN considerar la historia.

In [28]:
# esta funcion atributos presentes existe debido a que las modalidades poseen datasets con distinta cantidad de campos
atributos_presentes <- function( patributos )
{
  atributos <- unique( patributos )
  comun <- intersect( atributos, colnames(dataset) )

  return(  length( atributos ) == length( comun ) )
}

# el mes 1,2, ..12
if( atributos_presentes( c("foto_mes") ))
  dataset[, kmes := foto_mes %% 100]

# variable extraida de una tesis de maestria de Irlanda
if( atributos_presentes( c("mpayroll", "cliente_edad") ))
  dataset[, mpayroll_sobre_edad := mpayroll / cliente_edad]

In [29]:
# visualizo las columas del dataset a esta etapa
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"                     "kmes"
[57] "mpayroll_sobre_edad"

#### 9.3.1.4  FE_rf Feature Engineering de nuevas variables a partir de hojas de Random Forest

In [30]:
# No se implementa Feature Engineering a partir de Random Forest

#### 9.3.1.5  FEhist Feature Engineering historico

El Fature Engineering Histórico es la etapa que más aporta a la ganancia final, ya que enriquece cada registro del dataset con su historia.

Para cada campo del dataset original (*)
se crean lo siguientes campos de a partir de la historia
* lag1  lags de orden 1
* delta1  =  valor actual - lag1
* lag2  lags de orden 2
* delta2  = valor actual - lag2


(*) Excepto para los campos  <numero_de_cliente,  foto_mes,  clase_ternaria>

In [31]:
# Feature Engineering Historico

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente", "foto_mes", "clase_ternaria")
) )

# https://rdrr.io/cran/data.table/man/shift.html

# lags de orden 1
dataset[,
    paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# lags de orden 2
dataset[,
    paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# agrego los delta lags
for (vcol in cols_lagueables)
{
    dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
    dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}

Verificacion de los campos recien creados

In [32]:
ncol(dataset)
colnames(dataset)

[1] 273

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "internet"
  [4] "cliente_edad"
  [5] "cliente_antiguedad"
  [6] "mrentabilidad"
  [7] "mrentabilidad_annual"
  [8] "mcomisiones"
  [9] "mactivos_margen"
 [10] "mpasivos_margen"
 [11] "cproductos"
 [12] "mcuenta_corriente"
 [13] "mcaja_ahorro"
 [14] "cdescubierto_preacordado"
 [15] "mcuentas_saldo"
 [16] "ctarjeta_visa"
 [17] "ctarjeta_visa_transacciones"
 [18] "mtarjeta_visa_consumo"
 [19] "ctarjeta_master"
 [20] "ctarjeta_master_transacciones"
 [21] "mtarjeta_master_consumo"
 [22] "cprestamos_personales"
 [23] "mprestamos_personales"
 [24] "cpayroll_trx"
 [25] "mpayroll"
 [26] "mttarjeta_visa_debitos_automaticos"
 [27] "ccomisiones_mantenimiento"
 [28] "mcomisiones_mantenimiento"
 [29] "ccomisiones_otras"
 [30] "mtransferencias_recibidas"
 [31] "ccallcenter_transacciones"
 [32] "thomebanking"
 [33] "chomebanking_transacciones"
 [34] "ctrx_quarter"
 [35] "Master_status"
 [36] "Master_mfinanciacion_limite"
 [37] "Master_Fvencimiento"
 [38] "Master_msaldototal"
 [39] "Master_mlimitecompra"
 [40] "Master_fultimo_cierre"
 [41] "Master_fechaalta"
 [42] "Master_mconsumototal"
 [43] "Master_cconsumos"
 [44] "Master_mpagominimo"
 [45] "Visa_status"
 [46] "Visa_mfinanciacion_limite"
 [47] "Visa_Fvencimiento"
 [48] "Visa_msaldototal"
 [49] "Visa_mlimitecompra"
 [50] "Visa_fultimo_cierre"
 [51] "Visa_fechaalta"
 [52] "Visa_mconsumototal"
 [53] "Visa_cconsumos"
 [54] "Visa_mpagominimo"
 [55] "clase_ternaria"
 [56] "kmes"
 [57] "mpayroll_sobre_edad"
 [58] "internet_lag1"
 [59] "cliente_edad_lag1"
 [60] "cliente_antiguedad_lag1"
 [61] "mrentabilidad_lag1"
 [62] "mrentabilidad_annual_lag1"
 [63] "mcomisiones_lag1"
 [64] "mactivos_margen_lag1"
 [65] "mpasivos_margen_lag1"
 [66] "cproductos_lag1"
 [67] "mcuenta_corriente_lag1"
 [68] "mcaja_ahorro_lag1"
 [69] "cdescubierto_preacordado_lag1"
 [70] "mcuentas_saldo_lag1"
 [71] "ctarjeta_visa_lag1"
 [72] "ctarjeta_visa_transacciones_lag1"
 [73] "mtarjeta_visa_consumo_lag1"
 [74] "ctarjeta_master_lag1"
 [75] "ctarjeta_master_transacciones_lag1"
 [76] "mtarjeta_master_consumo_lag1"
 [77] "cprestamos_personales_lag1"
 [78] "mprestamos_personales_lag1"
 [79] "cpayroll_trx_lag1"
 [80] "mpayroll_lag1"
 [81] "mttarjeta_visa_debitos_automaticos_lag1"
 [82] "ccomisiones_mantenimiento_lag1"
 [83] "mcomisiones_mantenimiento_lag1"
 [84] "ccomisiones_otras_lag1"
 [85] "mtransferencias_recibidas_lag1"
 [86] "ccallcenter_transacciones_lag1"
 [87] "thomebanking_lag1"
 [88] "chomebanking_transacciones_lag1"
 [89] "ctrx_quarter_lag1"
 [90] "Master_status_lag1"
 [91] "Master_mfinanciacion_limite_lag1"
 [92] "Master_Fvencimiento_lag1"
 [93] "Master_msaldototal_lag1"
 [94] "Master_mlimitecompra_lag1"
 [95] "Master_fultimo_cierre_lag1"
 [96] "Master_fechaalta_lag1"
 [97] "Master_mconsumototal_lag1"
 [98] "Master_cconsumos_lag1"
 [99] "Master_mpagominimo_lag1"
[100] "Visa_status_lag1"
[101] "Visa_mfinanciacion_limite_lag1"
[102] "Visa_Fvencimiento_lag1"
[103] "Visa_msaldototal_lag1"
[104] "Visa_mlimitecompra_lag1"
[105] "Visa_fultimo_cierre_lag1"
[106] "Visa_fechaalta_lag1"
[107] "Visa_mconsumototal_lag1"
[108] "Visa_cconsumos_lag1"
[109] "Visa_mpagominimo_lag1"
[110] "kmes_lag1"
[111] "mpayroll_sobre_edad_lag1"
[112] "internet_lag2"
[113] "cliente_edad_lag2"
[114] "cliente_antiguedad_lag2"
[115] "mrentabilidad_lag2"
[116] "mrentabilidad_annual_lag2"
[117] "mcomisiones_lag2"
[118] "mactivos_margen_lag2"
[119] "mpasivos_margen_lag2"
[120] "cproductos_lag2"
[121] "mcuenta_corriente_lag2"
[122] "mcaja_ahorro_lag2"
[123] "cdescubierto_preacordado_lag2"
[124] "mcuentas_saldo_lag2"
[125] "ctarjeta_visa_lag2"
[126] "ctarjeta_visa_transacciones_lag2"
[127] "mtarjeta_visa_consumo_lag2"
[128] "ctarjeta_master_lag2"
[129] "ctarjeta_master_transacciones_lag2"
[130] "mtarjeta_master_consumo_lag2"
[131] "cprestamos_personales_lag2"
[132] "mprestamos_personales_lag2"
[133] "cpayroll_trx_lag2"
[134] "mpayroll_lag2"
[135] "mttarjeta_visa_debitos_automaticos_lag2"
[136] "ccomisiones_mantenimiento_lag2"
[137] "mcomisiones_mantenimiento_lag2"
[138] "ccomisiones_otras_lag2"
[139] "mtransferencias_recibidas_lag2"
[140] "ccallcenter_transacciones_lag2"
[141] "thomebanking_lag2"
[142] "chomebanking_transacciones_lag2"
[143] "ctrx_quarter_lag2"
[144] "Master_status_lag2"
[145] "Master_mfinanciacion_limite_lag2"
[146] "Master_Fvencimiento_lag2"
[147] "Master_msaldototal_lag2"
[148] "Master_mlimitecompra_lag2"
[149] "Master_fultimo_cierre_lag2"
[150] "Master_fechaalta_lag2"
[151] "Master_mconsumototal_lag2"
[152] "Master_cconsumos_lag2"
[153] "Master_mpagominimo_lag2"
[154] "Visa_status_lag2"
[155] "Visa_mfinanciacion_limite_lag2"
[156] "Visa_Fvencimiento_lag2"
[157] "Visa_msaldototal_lag2"
[158] "Visa_mlimitecompra_lag2"
[159] "Visa_fultimo_cierre_lag2"
[160] "Visa_fechaalta_lag2"
[161] "Visa_mconsumototal_lag2"
[162] "Visa_cconsumos_lag2"
[163] "Visa_mpagominimo_lag2"
[164] "kmes_lag2"
[165] "mpayroll_sobre_edad_lag2"
[166] "internet_delta1"
[167] "internet_delta2"
[168] "cliente_edad_delta1"
[169] "cliente_edad_delta2"
[170] "cliente_antiguedad_delta1"
[171] "cliente_antiguedad_delta2"
[172] "mrentabilidad_delta1"
[173] "mrentabilidad_delta2"
[174] "mrentabilidad_annual_delta1"
[175] "mrentabilidad_annual_delta2"
[176] "mcomisiones_delta1"
[177] "mcomisiones_delta2"
[178] "mactivos_margen_delta1"
[179] "mactivos_margen_delta2"
[180] "mpasivos_margen_delta1"
[181] "mpasivos_margen_delta2"
[182] "cproductos_delta1"
[183] "cproductos_delta2"
[184] "mcuenta_corriente_delta1"
[185] "mcuenta_corriente_delta2"
[186] "mcaja_ahorro_delta1"
[187] "mcaja_ahorro_delta2"
[188] "cdescubierto_preacordado_delta1"
[189] "cdescubierto_preacordado_delta2"
[190] "mcuentas_saldo_delta1"
[191] "mcuentas_saldo_delta2"
[192] "ctarjeta_visa_delta1"
[193] "ctarjeta_visa_delta2"
[194] "ctarjeta_visa_transacciones_delta1"
[195] "ctarjeta_visa_transacciones_delta2"
[196] "mtarjeta_visa_consumo_delta1"
[197] "mtarjeta_visa_consumo_delta2"
[198] "ctarjeta_master_delta1"
[199] "ctarjeta_master_delta2"
[200] "ctarjeta_master_transacciones_delta1"
[201] "ctarjeta_master_transacciones_delta2"
[202] "mtarjeta_master_consumo_delta1"
[203] "mtarjeta_master_consumo_delta2"
[204] "cprestamos_personales_delta1"
[205] "cprestamos_personales_delta2"
[206] "mprestamos_personales_delta1"
[207] "mprestamos_personales_delta2"
[208] "cpayroll_trx_delta1"
[209] "cpayroll_trx_delta2"
[210] "mpayroll_delta1"
[211] "mpayroll_delta2"
[212] "mttarjeta_visa_debitos_automaticos_delta1"
[213] "mttarjeta_visa_debitos_automaticos_delta2"
[214] "ccomisiones_mantenimiento_delta1"
[215] "ccomisiones_mantenimiento_delta2"
[216] "mcomisiones_mantenimiento_delta1"
[217] "mcomisiones_mantenimiento_delta2"
[218] "ccomisiones_otras_delta1"
[219] "ccomisiones_otras_delta2"
[220] "mtransferencias_recibidas_delta1"
[221] "mtransferencias_recibidas_delta2"
[222] "ccallcenter_transacciones_delta1"
[223] "ccallcenter_transacciones_delta2"
[224] "thomebanking_delta1"
[225] "thomebanking_delta2"
[226] "chomebanking_transacciones_delta1"
[227] "chomebanking_transacciones_delta2"
[228] "ctrx_quarter_delta1"
[229] "ctrx_quarter_delta2"
[230] "Master_status_delta1"
[231] "Master_status_delta2"
[232] "Master_mfinanciacion_limite_delta1"
[233] "Master_mfinanciacion_limite_delta2"
[234] "Master_Fvencimiento_delta1"
[235] "Master_Fvencimiento_delta2"
[236] "Master_msaldototal_delta1"
[237] "Master_msaldototal_delta2"
[238] "Master_mlimitecompra_delta1"
[239] "Master_mlimitecompra_delta2"
[240] "Master_fultimo_cierre_delta1"
[241] "Master_fultimo_cierre_delta2"
[242] "Master_fechaalta_delta1"
[243] "Master_fechaalta_delta2"
[244] "Master_mconsumototal_delta1"
[245] "Master_mconsumototal_delta2"
[246] "Master_cconsumos_delta1"
[247] "Master_cconsumos_delta2"
[248] "Master_mpagominimo_delta1"
[249] "Master_mpagominimo_delta2"
[250] "Visa_status_delta1"
[251] "Visa_status_delta2"
[252] "Visa_mfinanciacion_limite_delta1"
[253] "Visa_mfinanciacion_limite_delta2"
[254] "Visa_Fvencimiento_delta1"
[255] "Visa_Fvencimiento_delta2"
[256] "Visa_msaldototal_delta1"
[257] "Visa_msaldototal_delta2"
[258] "Visa_mlimitecompra_delta1"
[259] "Visa_mlimitecompra_delta2"
[260] "Visa_fultimo_cierre_delta1"
[261] "Visa_fultimo_cierre_delta2"
[262] "Visa_fechaalta_delta1"
[263] "Visa_fechaalta_delta2"
[264] "Visa_mconsumototal_delta1"
[265] "Visa_mconsumototal_delta2"
[266] "Visa_cconsumos_delta1"
[267] "Visa_cconsumos_delta2"
[268] "Visa_mpagominimo_delta1"
[269] "Visa_mpagominimo_delta2"
[270] "kmes_delta1"
[271] "kmes_delta2"
[272] "mpayroll_sobre_edad_delta1"
[273] "mpayroll_sobre_edad_delta2"

#### 9.3.1.6  FEhist Reduccion dimensionalidad con canaritos

Esta etapa solo se mostrará a la *modalidad Anlista Sr* por algun canal secreto de forma de no confundir a los *Analista Jr*  ni distraer con detalles operativos a la estratégica *Modalidad Gerencial*

In [33]:
# No se implementa la reduccion de la dimensionalidad con canaritos

### 9.3.2 Modelado

#### 9.3.2.1 Training Strategy

Se evalúa una estrategia temporal configurable. Los meses indicados en
`PARAM$meses_excluidos` se eliminan tanto del entrenamiento de Modelado como del
entrenamiento final de Producción, según la consigna del Experimento 4.

In [34]:
PARAM$trainingstrategy$validate <- c(202107)

meses_training_base <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)

PARAM$trainingstrategy$training <- setdiff(
  meses_training_base,
  PARAM$meses_excluidos
)

PARAM$trainingstrategy$training_pct <- 1.0
PARAM$trainingstrategy$positivos <- c("BAJA+1", "BAJA+2")

cat("Escenario:", PARAM$nombre_escenario, "\n")
cat("Meses excluidos:", PARAM$meses_excluidos, "\n")
cat("Meses de training:", PARAM$trainingstrategy$training, "\n")

Escenario: M2_sin_febrero_marzo_2020
Meses excluidos: 202002 202003
Meses de training: 201901 201902 201903 201904 201905 201906 201907 201908 201909 201910 201911 201912 202001 202004 202005 202006 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105

In [35]:
# seteo la clase01   1={BAJA+1, BAJA+2}   0={CONTINUA}
dataset[, clase01 := ifelse( clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0 )]

In [36]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

In [37]:
# preparo para que se puede hacer undersampling de los CONTINUA
#  solamente por un tema de VELOCIDAD
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset[, azar:=runif(nrow(dataset))]

# undersampling de los CONTINUA
dataset[, fold_train :=  foto_mes %in%  PARAM$trainingstrategy$training &
    (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
     azar < PARAM$trainingstrategy$training_pct ) ]


if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

dtrain <- lgb.Dataset(
  data= data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
  label= dataset[fold_train == TRUE, clase01],
  free_raw_data= TRUE
)

Loading required package: lightgbm

In [38]:
# datos de validation
dvalidate <- lgb.Dataset(
  data= data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
  label= dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
  free_raw_data= TRUE
)

nrow(dvalidate)

[1] 32938

####  9.3.2.2. Hyperparameter Tuning

* Clase binaria que se optimiza :  positivos = [ BAJA+1, BAJA+2 ]

* Metrica que se optimiza **AUC** Area Under Curve de la  ROC Curve

es muy importante notar que intencionalmente  **NO** se está optimizando la funcion de ganancia del problema

* Parametros no default, fijos de LightGBM que no se optimizan
  * max_bin = 31 , Alienigenas Ancestrales contruyeron las pirámides y dejaron a la humanidad en un jeroglifico  *max_bin=31*
  * feature_fraction = 0.5  para poner algo que generalmente no falla
  * learning_rate = 0.03  para que aprenda lento

* Parámetros optimizados mediante Grid Search multisemilla:
  * `num_leaves`: 64, 128, 256, 384 y 512
  * `min_data_in_leaf`: 64, 256, 512, 1024 y 2048
  * `feature_fraction`: 0.5 y 0.8

Cada una de las 50 configuraciones se evalúa con todas las semillas configuradas.

In [39]:
# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "auc",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  seed= PARAM$semilla_primigenia,
  max_bin= 31,
  learning_rate= 0.03,
  feature_fraction= 0.5,
  num_iterations= 2048,  # valor grande, lo limita early_stopping_rounds
  early_stopping_rounds= 200,
  num_leaves= 64,
  min_data_in_leaf= 128
)

In [40]:
# En  x llegan los parametros moviles de LightGBM
#  devuelve la AUC en validate del modelo entrenado
#  en el parametro x llegan los hiperparámetros que se estan optimizando

Estimar_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM
  modelo_train <- lgb.train(
    data= dtrain,
    valids= list(valid = dvalidate),
    eval= "auc",
    param= param_completo,
    verbose= -100
  )

  # recupero la AUC en validation
  AUC <- modelo_train$record_evals$valid$auc$eval[[modelo_train$best_iter]]

  message(format(Sys.time(), "%a %b %d %X %Y  "),
    toString(x),
    " niter ", modelo_train$best_iter,
    " AUC ", AUC
  )

  # hago espacio en la memoria
  niter <- modelo_train$best_iter
  rm(modelo_train)
  gc(full= TRUE, verbose= FALSE)

  return( list(AUC, niter))
}

seteo del Grid Search

In [41]:
# Producto cartesiano: 50 configuraciones por cada semilla
tb_nueva <- CJ(
  num_leaves = c(64, 128, 256, 384, 512),
  min_data_in_leaf = c(64, 256, 512, 1024, 2048),
  feature_fraction = c(0.5, 0.8),
  seed = PARAM$semillas
)

tb_nueva[, `:=`(AUC = NA_real_, num_iterations = NA_integer_)]

PARAM$archivo_grid_detalle <- paste0(
  "grid_detalle_", PARAM$nombre_escenario, ".txt"
)

# Si existe un checkpoint compatible, recupera lo ya calculado.
if (file.exists(PARAM$archivo_grid_detalle)) {
  checkpoint <- fread(PARAM$archivo_grid_detalle)
  claves <- c("num_leaves", "min_data_in_leaf", "feature_fraction", "seed")

  if (nrow(checkpoint) == nrow(tb_nueva) &&
      fsetequal(checkpoint[, ..claves], tb_nueva[, ..claves])) {
    setkeyv(tb_nueva, claves)
    setkeyv(checkpoint, claves)
    tb_nueva[checkpoint, `:=`(
      AUC = i.AUC,
      num_iterations = i.num_iterations
    )]
    setorderv(tb_nueva, claves)
    cat("Checkpoint recuperado. Resultados completos:",
        sum(!is.na(tb_nueva$AUC)), "\n")
  } else {
    stop("El checkpoint no coincide con las semillas o la grilla actual")
  }
}

nrow(tb_nueva)

[1] 350

##### Corrida del Grid Search,  aqui se hace el trabajo pesado
<br> por favor no se asuste con los warnings que pudieran aparecer
<br> ATENCION, la siguiente celda demora 65 minutos
<br> una Analista Jr  debe ser capaz de tolerar estoicamente esta tortura
<br> (y masticar chicle al mismo tiempo)

In [42]:
# Calcula solamente combinaciones pendientes y guarda después de cada modelo.
pendientes <- which(is.na(tb_nueva$AUC))

for (i in pendientes) {
  x <- as.list(tb_nueva[i, .(
    num_leaves,
    min_data_in_leaf,
    feature_fraction,
    seed
  )])

  resultado <- Estimar_AUC_lightgbm(x)
  set(tb_nueva, i = i, j = "AUC", value = as.numeric(resultado[[1]]))
  set(tb_nueva, i = i, j = "num_iterations",
      value = as.integer(resultado[[2]]))

  fwrite(tb_nueva, PARAM$archivo_grid_detalle, sep = "\t")
}

stopifnot(sum(is.na(tb_nueva$AUC)) == 0L)
cat("Grid Search completo:", nrow(tb_nueva), "modelos\n")

Wed Sep 09 19:17:49 2026  64, 64, 0.5, 163687 niter 95 AUC 0.931229130253651

Wed Sep 09 19:18:29 2026  64, 64, 0.5, 365305 niter 78 AUC 0.93004174213611

Wed Sep 09 19:19:06 2026  64, 64, 0.5, 613037 niter 94 AUC 0.930550037430729

Wed Sep 09 19:19:45 2026  64, 64, 0.5, 648983 niter 113 AUC 0.931189181673323

Wed Sep 09 19:20:21 2026  64, 64, 0.5, 690506 niter 92 AUC 0.932153366598044

Wed Sep 09 19:21:03 2026  64, 64, 0.5, 700001 niter 102 AUC 0.929946347966211

Wed Sep 09 19:21:40 2026  64, 64, 0.5, 804528 niter 102 AUC 0.929350159186336

Wed Sep 09 19:22:05 2026  64, 64, 0.8, 163687 niter 171 AUC 0.930197373081807

Wed Sep 09 19:22:31 2026  64, 64, 0.8, 365305 niter 86 AUC 0.929576435346874

Wed Sep 09 19:22:58 2026  64, 64, 0.8, 613037 niter 209 AUC 0.929870845479816

Wed Sep 09 19:23:18 2026  64, 64, 0.8, 648983 niter 87 AUC 0.930484216444779

Wed Sep 09 19:23:45 2026  64, 64, 0.8, 690506 niter 200 AUC 0.930282953580609

Wed Sep 09 19:24:05 2026  64, 64, 0.8, 700001 niter 86 AUC 0.930310114650113

Wed Sep 09 19:24:26 2026  64, 64, 0.8, 804528 niter 94 AUC 0.930850263072471

Wed Sep 09 19:25:09 2026  64, 256, 0.5, 163687 niter 109 AUC 0.931439975490274

Wed Sep 09 19:25:58 2026  64, 256, 0.5, 365305 niter 213 AUC 0.932674251147506

Wed Sep 09 19:26:45 2026  64, 256, 0.5, 613037 niter 146 AUC 0.931126136271117

Wed Sep 09 19:27:21 2026  64, 256, 0.5, 648983 niter 95 AUC 0.931525952501039

Wed Sep 09 19:27:59 2026  64, 256, 0.5, 690506 niter 98 AUC 0.930887403026391

Wed Sep 09 19:28:40 2026  64, 256, 0.5, 700001 niter 90 AUC 0.930085754964065

Wed Sep 09 19:29:22 2026  64, 256, 0.5, 804528 niter 150 AUC 0.930976254748892

Wed Sep 09 19:29:44 2026  64, 256, 0.8, 163687 niter 81 AUC 0.93130886220099

Wed Sep 09 19:30:05 2026  64, 256, 0.8, 365305 niter 89 AUC 0.930835261703183

Wed Sep 09 19:30:26 2026  64, 256, 0.8, 613037 niter 96 AUC 0.930649826274892

Wed Sep 09 19:30:52 2026  64, 256, 0.8, 648983 niter 101 AUC 0.930308264260949

Wed Sep 09 19:31:14 2026  64, 256, 0.8, 690506 niter 90 AUC 0.931080273053999

Wed Sep 09 19:31:34 2026  64, 256, 0.8, 700001 niter 82 AUC 0.93085317082687

Wed Sep 09 19:31:58 2026  64, 256, 0.8, 804528 niter 128 AUC 0.931945065646521

Wed Sep 09 19:32:34 2026  64, 512, 0.5, 163687 niter 99 AUC 0.932010357949853

Wed Sep 09 19:33:24 2026  64, 512, 0.5, 365305 niter 169 AUC 0.931504309556361

Wed Sep 09 19:34:10 2026  64, 512, 0.5, 613037 niter 162 AUC 0.931440041575601

Wed Sep 09 19:35:02 2026  64, 512, 0.5, 648983 niter 188 AUC 0.9320504717435

Wed Sep 09 19:35:54 2026  64, 512, 0.5, 690506 niter 163 AUC 0.930330964570863

Wed Sep 09 19:36:38 2026  64, 512, 0.5, 700001 niter 149 AUC 0.930988844003735

Wed Sep 09 19:37:20 2026  64, 512, 0.5, 804528 niter 102 AUC 0.931317486336198

Wed Sep 09 19:37:42 2026  64, 512, 0.8, 163687 niter 79 AUC 0.932538544927978

Wed Sep 09 19:38:05 2026  64, 512, 0.8, 365305 niter 98 AUC 0.932173291324212

Wed Sep 09 19:38:26 2026  64, 512, 0.8, 613037 niter 80 AUC 0.932127328979103

Wed Sep 09 19:38:53 2026  64, 512, 0.8, 648983 niter 85 AUC 0.933139161424778

Wed Sep 09 19:39:15 2026  64, 512, 0.8, 690506 niter 89 AUC 0.932541849194341

Wed Sep 09 19:39:37 2026  64, 512, 0.8, 700001 niter 88 AUC 0.932340982842134

Wed Sep 09 19:40:02 2026  64, 512, 0.8, 804528 niter 142 AUC 0.932454087879739

Wed Sep 09 19:40:46 2026  64, 1024, 0.5, 163687 niter 145 AUC 0.932571290207635

Wed Sep 09 19:41:36 2026  64, 1024, 0.5, 365305 niter 164 AUC 0.932495820763904

Wed Sep 09 19:42:20 2026  64, 1024, 0.5, 613037 niter 143 AUC 0.932952272119288

Wed Sep 09 19:43:09 2026  64, 1024, 0.5, 648983 niter 153 AUC 0.933385659695458

Wed Sep 09 19:43:48 2026  64, 1024, 0.5, 690506 niter 96 AUC 0.931965849481944

Wed Sep 09 19:44:31 2026  64, 1024, 0.5, 700001 niter 135 AUC 0.931945660414466

Wed Sep 09 19:45:18 2026  64, 1024, 0.5, 804528 niter 106 AUC 0.932377362814791

Wed Sep 09 19:45:45 2026  64, 1024, 0.8, 163687 niter 151 AUC 0.933511915713188

Wed Sep 09 19:46:09 2026  64, 1024, 0.8, 365305 niter 94 AUC 0.932611470086609

Wed Sep 09 19:46:39 2026  64, 1024, 0.8, 613037 niter 201 AUC 0.93254221266364

Wed Sep 09 19:47:06 2026  64, 1024, 0.8, 648983 niter 85 AUC 0.932416187944556

Wed Sep 09 19:47:31 2026  64, 1024, 0.8, 690506 niter 130 AUC 0.932652839501473

Wed Sep 09 19:47:58 2026  64, 1024, 0.8, 700001 niter 148 AUC 0.933293140237294

Wed Sep 09 19:48:22 2026  64, 1024, 0.8, 804528 niter 118 AUC 0.932995822349952

Wed Sep 09 19:49:08 2026  64, 2048, 0.5, 163687 niter 112 AUC 0.932221963167739

Wed Sep 09 19:49:53 2026  64, 2048, 0.5, 365305 niter 159 AUC 0.931914798566636

Wed Sep 09 19:50:33 2026  64, 2048, 0.5, 613037 niter 103 AUC 0.932080804908712

Wed Sep 09 19:51:16 2026  64, 2048, 0.5, 648983 niter 94 AUC 0.932031207870604

Wed Sep 09 19:52:06 2026  64, 2048, 0.5, 690506 niter 186 AUC 0.932822678792531

Wed Sep 09 19:52:52 2026  64, 2048, 0.5, 700001 niter 143 AUC 0.932161032496006

Wed Sep 09 19:53:48 2026  64, 2048, 0.5, 804528 niter 200 AUC 0.930931845408973

Wed Sep 09 19:54:19 2026  64, 2048, 0.8, 163687 niter 172 AUC 0.932897024785698

Wed Sep 09 19:54:49 2026  64, 2048, 0.8, 365305 niter 151 AUC 0.93291387654415

Wed Sep 09 19:55:24 2026  64, 2048, 0.8, 613037 niter 147 AUC 0.932292211870617

Wed Sep 09 19:55:52 2026  64, 2048, 0.8, 648983 niter 132 AUC 0.932804240986226

Wed Sep 09 19:56:22 2026  64, 2048, 0.8, 690506 niter 146 AUC 0.931905348364838

Wed Sep 09 19:56:49 2026  64, 2048, 0.8, 700001 niter 131 AUC 0.932327171008737

Wed Sep 09 19:57:21 2026  64, 2048, 0.8, 804528 niter 130 AUC 0.932255798855296

Wed Sep 09 19:58:01 2026  128, 64, 0.5, 163687 niter 92 AUC 0.929895264008239

Wed Sep 09 19:58:41 2026  128, 64, 0.5, 365305 niter 100 AUC 0.931538112201255

Wed Sep 09 19:59:25 2026  128, 64, 0.5, 613037 niter 90 AUC 0.931372964968432

Wed Sep 09 20:00:14 2026  128, 64, 0.5, 648983 niter 162 AUC 0.931714361769057

Wed Sep 09 20:00:54 2026  128, 64, 0.5, 690506 niter 96 AUC 0.929275747107842

Wed Sep 09 20:01:37 2026  128, 64, 0.5, 700001 niter 85 AUC 0.93022697930842

Wed Sep 09 20:02:20 2026  128, 64, 0.5, 804528 niter 110 AUC 0.929933857839359

Wed Sep 09 20:02:49 2026  128, 64, 0.8, 163687 niter 134 AUC 0.930462375244119

Wed Sep 09 20:03:19 2026  128, 64, 0.8, 365305 niter 132 AUC 0.929582845623618

Wed Sep 09 20:03:50 2026  128, 64, 0.8, 613037 niter 100 AUC 0.929526111370166

Wed Sep 09 20:04:15 2026  128, 64, 0.8, 648983 niter 89 AUC 0.931751666936295

Wed Sep 09 20:04:44 2026  128, 64, 0.8, 690506 niter 120 AUC 0.930689279215266

Wed Sep 09 20:05:10 2026  128, 64, 0.8, 700001 niter 81 AUC 0.93099171871547

Wed Sep 09 20:05:48 2026  128, 64, 0.8, 804528 niter 173 AUC 0.930348906737214

Wed Sep 09 20:06:29 2026  128, 256, 0.5, 163687 niter 95 AUC 0.931519938736258

Wed Sep 09 20:07:07 2026  128, 256, 0.5, 365305 niter 77 AUC 0.932232735076083

Wed Sep 09 20:08:04 2026  128, 256, 0.5, 613037 niter 188 AUC 0.929927546690605

Wed Sep 09 20:08:44 2026  128, 256, 0.5, 648983 niter 94 AUC 0.932373463780482

Wed Sep 09 20:09:24 2026  128, 256, 0.5, 690506 niter 94 AUC 0.931568412323803

Wed Sep 09 20:10:08 2026  128, 256, 0.5, 700001 niter 88 AUC 0.931196087590021

Wed Sep 09 20:10:48 2026  128, 256, 0.5, 804528 niter 94 AUC 0.931342565717893

Wed Sep 09 20:11:15 2026  128, 256, 0.8, 163687 niter 96 AUC 0.930727476534422

Wed Sep 09 20:11:46 2026  128, 256, 0.8, 365305 niter 93 AUC 0.931410864903616

Wed Sep 09 20:12:13 2026  128, 256, 0.8, 613037 niter 99 AUC 0.931450780441281

Wed Sep 09 20:12:42 2026  128, 256, 0.8, 648983 niter 112 AUC 0.932496316403859

Wed Sep 09 20:13:07 2026  128, 256, 0.8, 690506 niter 85 AUC 0.931577466013638

Wed Sep 09 20:13:42 2026  128, 256, 0.8, 700001 niter 154 AUC 0.931090318023742

Wed Sep 09 20:14:07 2026  128, 256, 0.8, 804528 niter 87 AUC 0.930603500460483

Wed Sep 09 20:14:48 2026  128, 512, 0.5, 163687 niter 95 AUC 0.932484189746306

Wed Sep 09 20:15:29 2026  128, 512, 0.5, 365305 niter 94 AUC 0.931868737093536

Wed Sep 09 20:16:22 2026  128, 512, 0.5, 613037 niter 154 AUC 0.93289603350579

Wed Sep 09 20:17:05 2026  128, 512, 0.5, 648983 niter 114 AUC 0.933413547703561

Wed Sep 09 20:17:56 2026  128, 512, 0.5, 690506 niter 141 AUC 0.933393127337438

Wed Sep 09 20:18:39 2026  128, 512, 0.5, 700001 niter 108 AUC 0.931118007775864

Wed Sep 09 20:19:17 2026  128, 512, 0.5, 804528 niter 74 AUC 0.931206297773083

Wed Sep 09 20:19:52 2026  128, 512, 0.8, 163687 niter 133 AUC 0.931662881299121

Wed Sep 09 20:20:18 2026  128, 512, 0.8, 365305 niter 78 AUC 0.932061805377125

Wed Sep 09 20:20:45 2026  128, 512, 0.8, 613037 niter 97 AUC 0.931782099229498

Wed Sep 09 20:21:11 2026  128, 512, 0.8, 648983 niter 79 AUC 0.932593296621612

Wed Sep 09 20:21:41 2026  128, 512, 0.8, 690506 niter 122 AUC 0.932134796621084

Wed Sep 09 20:22:16 2026  128, 512, 0.8, 700001 niter 139 AUC 0.933248334385412

Wed Sep 09 20:22:43 2026  128, 512, 0.8, 804528 niter 84 AUC 0.931168563051218

Wed Sep 09 20:23:25 2026  128, 1024, 0.5, 163687 niter 94 AUC 0.932556553179656

Wed Sep 09 20:24:09 2026  128, 1024, 0.5, 365305 niter 82 AUC 0.932292476211926

Wed Sep 09 20:24:53 2026  128, 1024, 0.5, 613037 niter 101 AUC 0.93383900504046

Wed Sep 09 20:25:35 2026  128, 1024, 0.5, 648983 niter 101 AUC 0.933572416830294

Wed Sep 09 20:26:21 2026  128, 1024, 0.5, 690506 niter 85 AUC 0.933118344546692

Wed Sep 09 20:27:05 2026  128, 1024, 0.5, 700001 niter 114 AUC 0.932186871858964

Wed Sep 09 20:27:48 2026  128, 1024, 0.5, 804528 niter 98 AUC 0.931815835789064

Wed Sep 09 20:28:24 2026  128, 1024, 0.8, 163687 niter 114 AUC 0.933109158686203

Wed Sep 09 20:28:56 2026  128, 1024, 0.8, 365305 niter 126 AUC 0.932806091375389

Wed Sep 09 20:29:29 2026  128, 1024, 0.8, 613037 niter 137 AUC 0.932837878417801

Wed Sep 09 20:30:02 2026  128, 1024, 0.8, 648983 niter 80 AUC 0.932395371066469

Wed Sep 09 20:30:35 2026  128, 1024, 0.8, 690506 niter 135 AUC 0.933833718214279

Wed Sep 09 20:31:06 2026  128, 1024, 0.8, 700001 niter 106 AUC 0.933294263687857

Wed Sep 09 20:31:34 2026  128, 1024, 0.8, 804528 niter 80 AUC 0.932403631732377

Wed Sep 09 20:32:24 2026  128, 2048, 0.5, 163687 niter 101 AUC 0.933113388147147

Wed Sep 09 20:33:11 2026  128, 2048, 0.5, 365305 niter 103 AUC 0.932181585032784

Wed Sep 09 20:34:02 2026  128, 2048, 0.5, 613037 niter 101 AUC 0.93251353163161

Wed Sep 09 20:34:51 2026  128, 2048, 0.5, 648983 niter 124 AUC 0.932668567809361

Wed Sep 09 20:35:47 2026  128, 2048, 0.5, 690506 niter 164 AUC 0.932753751796199

Wed Sep 09 20:36:42 2026  128, 2048, 0.5, 700001 niter 132 AUC 0.932491393046978

Wed Sep 09 20:37:28 2026  128, 2048, 0.5, 804528 niter 103 AUC 0.931261346850691

Wed Sep 09 20:38:15 2026  128, 2048, 0.8, 163687 niter 166 AUC 0.932626471455897

Wed Sep 09 20:38:55 2026  128, 2048, 0.8, 365305 niter 132 AUC 0.93178302442408

Wed Sep 09 20:39:29 2026  128, 2048, 0.8, 613037 niter 105 AUC 0.932040889371047

Wed Sep 09 20:40:03 2026  128, 2048, 0.8, 648983 niter 90 AUC 0.932418699186992

Wed Sep 09 20:40:44 2026  128, 2048, 0.8, 690506 niter 126 AUC 0.933337285235903

Wed Sep 09 20:41:22 2026  128, 2048, 0.8, 700001 niter 135 AUC 0.932440969942278

Wed Sep 09 20:41:57 2026  128, 2048, 0.8, 804528 niter 113 AUC 0.932208349590324

Wed Sep 09 20:43:01 2026  256, 64, 0.5, 163687 niter 166 AUC 0.931667044674739

Wed Sep 09 20:43:50 2026  256, 64, 0.5, 365305 niter 105 AUC 0.930417833733546

Wed Sep 09 20:44:43 2026  256, 64, 0.5, 613037 niter 89 AUC 0.93006913450426

Wed Sep 09 20:45:33 2026  256, 64, 0.5, 648983 niter 110 AUC 0.932029588780086

Wed Sep 09 20:46:22 2026  256, 64, 0.5, 690506 niter 70 AUC 0.93113462823567

Wed Sep 09 20:47:12 2026  256, 64, 0.5, 700001 niter 111 AUC 0.93066036688459

Wed Sep 09 20:47:58 2026  256, 64, 0.5, 804528 niter 85 AUC 0.931510918089087

Wed Sep 09 20:48:40 2026  256, 64, 0.8, 163687 niter 101 AUC 0.931452036062499

Wed Sep 09 20:49:15 2026  256, 64, 0.8, 365305 niter 85 AUC 0.928259288689258

Wed Sep 09 20:49:53 2026  256, 64, 0.8, 613037 niter 108 AUC 0.930550797411993

Wed Sep 09 20:50:30 2026  256, 64, 0.8, 648983 niter 67 AUC 0.931063520423538

Wed Sep 09 20:51:05 2026  256, 64, 0.8, 690506 niter 77 AUC 0.930764186933715

Wed Sep 09 20:51:47 2026  256, 64, 0.8, 700001 niter 154 AUC 0.930727840003722

Wed Sep 09 20:52:29 2026  256, 64, 0.8, 804528 niter 108 AUC 0.928435009574442

Wed Sep 09 20:53:17 2026  256, 256, 0.5, 163687 niter 93 AUC 0.932044061466756

Wed Sep 09 20:54:06 2026  256, 256, 0.5, 365305 niter 92 AUC 0.932269643731357

Wed Sep 09 20:54:59 2026  256, 256, 0.5, 613037 niter 92 AUC 0.930305951274495

Wed Sep 09 20:55:51 2026  256, 256, 0.5, 648983 niter 121 AUC 0.931444469292527

Wed Sep 09 20:56:44 2026  256, 256, 0.5, 690506 niter 89 AUC 0.932990403353117

Wed Sep 09 20:57:31 2026  256, 256, 0.5, 700001 niter 88 AUC 0.932472525686045

Wed Sep 09 20:58:21 2026  256, 256, 0.5, 804528 niter 111 AUC 0.932086356076202

Wed Sep 09 20:59:02 2026  256, 256, 0.8, 163687 niter 85 AUC 0.929393742459664

Wed Sep 09 20:59:46 2026  256, 256, 0.8, 365305 niter 146 AUC 0.929825709201298

Wed Sep 09 21:00:22 2026  256, 256, 0.8, 613037 niter 92 AUC 0.930972454842574

Wed Sep 09 21:01:04 2026  256, 256, 0.8, 648983 niter 88 AUC 0.933004049973196

Wed Sep 09 21:01:40 2026  256, 256, 0.8, 690506 niter 86 AUC 0.931162813627746

Wed Sep 09 21:02:17 2026  256, 256, 0.8, 700001 niter 91 AUC 0.931586288404827

Wed Sep 09 21:03:00 2026  256, 256, 0.8, 804528 niter 105 AUC 0.931032823789026

Wed Sep 09 21:03:50 2026  256, 512, 0.5, 163687 niter 95 AUC 0.93211173284187

Wed Sep 09 21:04:46 2026  256, 512, 0.5, 365305 niter 105 AUC 0.932475466483108

Wed Sep 09 21:05:33 2026  256, 512, 0.5, 613037 niter 87 AUC 0.931282989795368

Wed Sep 09 21:06:27 2026  256, 512, 0.5, 648983 niter 113 AUC 0.932743376399819

Wed Sep 09 21:07:18 2026  256, 512, 0.5, 690506 niter 80 AUC 0.93162782303301

Wed Sep 09 21:08:09 2026  256, 512, 0.5, 700001 niter 100 AUC 0.931828755470543

Wed Sep 09 21:09:03 2026  256, 512, 0.5, 804528 niter 84 AUC 0.933286498661904

Wed Sep 09 21:09:39 2026  256, 512, 0.8, 163687 niter 73 AUC 0.933254843790147

Wed Sep 09 21:10:15 2026  256, 512, 0.8, 365305 niter 59 AUC 0.931732700447371

Wed Sep 09 21:11:01 2026  256, 512, 0.8, 613037 niter 115 AUC 0.932648874381838

Wed Sep 09 21:11:40 2026  256, 512, 0.8, 648983 niter 96 AUC 0.93251062387721

Wed Sep 09 21:12:19 2026  256, 512, 0.8, 690506 niter 83 AUC 0.93201815601847

Wed Sep 09 21:13:03 2026  256, 512, 0.8, 700001 niter 87 AUC 0.931928544314706

Wed Sep 09 21:13:43 2026  256, 512, 0.8, 804528 niter 104 AUC 0.931628054331655

Wed Sep 09 21:14:34 2026  256, 1024, 0.5, 163687 niter 98 AUC 0.933301533073856

Wed Sep 09 21:15:28 2026  256, 1024, 0.5, 365305 niter 78 AUC 0.932022187223433

Wed Sep 09 21:16:22 2026  256, 1024, 0.5, 613037 niter 103 AUC 0.933084773200444

Wed Sep 09 21:17:19 2026  256, 1024, 0.5, 648983 niter 101 AUC 0.93420439081488

Wed Sep 09 21:18:12 2026  256, 1024, 0.5, 690506 niter 103 AUC 0.933583981762564

Wed Sep 09 21:19:10 2026  256, 1024, 0.5, 700001 niter 105 AUC 0.932521990553499

Wed Sep 09 21:20:03 2026  256, 1024, 0.5, 804528 niter 110 AUC 0.932239938376754

Wed Sep 09 21:20:42 2026  256, 1024, 0.8, 163687 niter 67 AUC 0.933553879895998

Wed Sep 09 21:21:33 2026  256, 1024, 0.8, 365305 niter 107 AUC 0.933912756265682

Wed Sep 09 21:22:17 2026  256, 1024, 0.8, 613037 niter 107 AUC 0.933074794316027

Wed Sep 09 21:23:06 2026  256, 1024, 0.8, 648983 niter 108 AUC 0.932028134902886

Wed Sep 09 21:23:50 2026  256, 1024, 0.8, 690506 niter 117 AUC 0.933669165749402

Wed Sep 09 21:24:36 2026  256, 1024, 0.8, 700001 niter 129 AUC 0.931904158828947

Wed Sep 09 21:25:23 2026  256, 1024, 0.8, 804528 niter 108 AUC 0.932110411135325

Wed Sep 09 21:26:16 2026  256, 2048, 0.5, 163687 niter 98 AUC 0.932878256552757

Wed Sep 09 21:27:23 2026  256, 2048, 0.5, 365305 niter 158 AUC 0.932998201421733

Wed Sep 09 21:28:16 2026  256, 2048, 0.5, 613037 niter 103 AUC 0.932723682972296

Wed Sep 09 21:29:17 2026  256, 2048, 0.5, 648983 niter 123 AUC 0.932618541216626

Wed Sep 09 21:30:16 2026  256, 2048, 0.5, 690506 niter 127 AUC 0.932328624885937

Wed Sep 09 21:31:23 2026  256, 2048, 0.5, 700001 niter 143 AUC 0.930974800871692

Wed Sep 09 21:32:23 2026  256, 2048, 0.5, 804528 niter 132 AUC 0.932535339789605

Wed Sep 09 21:33:19 2026  256, 2048, 0.8, 163687 niter 129 AUC 0.932306486301305

Wed Sep 09 21:34:10 2026  256, 2048, 0.8, 365305 niter 134 AUC 0.932666783505525

Wed Sep 09 21:34:58 2026  256, 2048, 0.8, 613037 niter 113 AUC 0.932951479095361

Wed Sep 09 21:35:55 2026  256, 2048, 0.8, 648983 niter 137 AUC 0.933297105356929

Wed Sep 09 21:36:52 2026  256, 2048, 0.8, 690506 niter 146 AUC 0.933172600600372

Wed Sep 09 21:37:49 2026  256, 2048, 0.8, 700001 niter 133 AUC 0.933874360690544

Wed Sep 09 21:38:39 2026  256, 2048, 0.8, 804528 niter 125 AUC 0.933335368761413

Wed Sep 09 21:39:35 2026  384, 64, 0.5, 163687 niter 78 AUC 0.930739074509356

Wed Sep 09 21:40:31 2026  384, 64, 0.5, 365305 niter 107 AUC 0.928290811390361

Wed Sep 09 21:41:48 2026  384, 64, 0.5, 613037 niter 190 AUC 0.929955038186746

Wed Sep 09 21:42:48 2026  384, 64, 0.5, 648983 niter 121 AUC 0.930817055195523

Wed Sep 09 21:43:50 2026  384, 64, 0.5, 690506 niter 117 AUC 0.930185345552246

Wed Sep 09 21:44:46 2026  384, 64, 0.5, 700001 niter 110 AUC 0.930294320256898

Wed Sep 09 21:45:42 2026  384, 64, 0.5, 804528 niter 84 AUC 0.93211956395315

Wed Sep 09 21:46:30 2026  384, 64, 0.8, 163687 niter 121 AUC 0.931225198176679

Wed Sep 09 21:47:17 2026  384, 64, 0.8, 365305 niter 111 AUC 0.929255194571064

Wed Sep 09 21:48:27 2026  384, 64, 0.8, 613037 niter 246 AUC 0.931210395063373

Wed Sep 09 21:49:09 2026  384, 64, 0.8, 648983 niter 89 AUC 0.931266468463553

Wed Sep 09 21:49:58 2026  384, 64, 0.8, 690506 niter 93 AUC 0.929994920681747

Wed Sep 09 21:50:45 2026  384, 64, 0.8, 700001 niter 114 AUC 0.931740928070615

Wed Sep 09 21:51:36 2026  384, 64, 0.8, 804528 niter 111 AUC 0.930484844255388

Wed Sep 09 21:52:32 2026  384, 256, 0.5, 163687 niter 104 AUC 0.93104888252355

Wed Sep 09 21:53:24 2026  384, 256, 0.5, 365305 niter 82 AUC 0.932113087591079

Wed Sep 09 21:54:29 2026  384, 256, 0.5, 613037 niter 118 AUC 0.929907258495137

Wed Sep 09 21:55:18 2026  384, 256, 0.5, 648983 niter 69 AUC 0.931303443204155

Wed Sep 09 21:56:16 2026  384, 256, 0.5, 690506 niter 85 AUC 0.931987195042649

Wed Sep 09 21:57:16 2026  384, 256, 0.5, 700001 niter 116 AUC 0.931556153495597

Wed Sep 09 21:58:20 2026  384, 256, 0.5, 804528 niter 77 AUC 0.930053703580344

Wed Sep 09 21:59:05 2026  384, 256, 0.8, 163687 niter 78 AUC 0.929390999918583

Wed Sep 09 21:59:57 2026  384, 256, 0.8, 365305 niter 93 AUC 0.930972620055892

Wed Sep 09 22:00:48 2026  384, 256, 0.8, 613037 niter 111 AUC 0.931156337265675

Wed Sep 09 22:01:34 2026  384, 256, 0.8, 648983 niter 81 AUC 0.930313518044466

Wed Sep 09 22:02:25 2026  384, 256, 0.8, 690506 niter 89 AUC 0.930554828616956

Wed Sep 09 22:03:12 2026  384, 256, 0.8, 700001 niter 90 AUC 0.930568177853062

Wed Sep 09 22:04:02 2026  384, 256, 0.8, 804528 niter 76 AUC 0.930859382847633

Wed Sep 09 22:04:57 2026  384, 512, 0.5, 163687 niter 90 AUC 0.931270797052489

Wed Sep 09 22:06:02 2026  384, 512, 0.5, 365305 niter 109 AUC 0.932929670937365

Wed Sep 09 22:06:57 2026  384, 512, 0.5, 613037 niter 91 AUC 0.931857700843883

Wed Sep 09 22:07:58 2026  384, 512, 0.5, 648983 niter 95 AUC 0.932280184341055

Wed Sep 09 22:08:55 2026  384, 512, 0.5, 690506 niter 94 AUC 0.932188259650837

Wed Sep 09 22:10:00 2026  384, 512, 0.5, 700001 niter 116 AUC 0.932432577105716

Wed Sep 09 22:10:53 2026  384, 512, 0.5, 804528 niter 82 AUC 0.932448107157622

Wed Sep 09 22:11:41 2026  384, 512, 0.8, 163687 niter 78 AUC 0.932755370886717

Wed Sep 09 22:12:34 2026  384, 512, 0.8, 365305 niter 82 AUC 0.931903564061001

Wed Sep 09 22:13:23 2026  384, 512, 0.8, 613037 niter 85 AUC 0.932580839537424

Wed Sep 09 22:14:15 2026  384, 512, 0.8, 648983 niter 77 AUC 0.932882618184356


Grid Search completo: 350 modelos

la optimizacion de hiperparámetros de tipo  Grid Search ha corrido, extraigo los mejores hiperparametros

In [43]:
# Guarda el detalle completo sin duplicar ejecuciones anteriores.
fwrite(
  tb_nueva,
  file = PARAM$archivo_grid_detalle,
  sep = "\t"
)

tb_nueva

    num_leaves min_data_in_leaf feature_fraction seed   AUC
1   64          64              0.5              163687 0.9312291
2   64          64              0.5              365305 0.9300417
3   64          64              0.5              613037 0.9305500
4   64          64              0.5              648983 0.9311892
5   64          64              0.5              690506 0.9321534
6   64          64              0.5              700001 0.9299463
7   64          64              0.5              804528 0.9293502
8   64          64              0.8              163687 0.9301974
9   64          64              0.8              365305 0.9295764
10  64          64              0.8              613037 0.9298708
11  64          64              0.8              648983 0.9304842
12  64          64              0.8              690506 0.9302830
13  64          64              0.8              700001 0.9303101
14  64          64              0.8              804528 0.9308503
15  64         256              0.5              163687 0.9314400
16  64         256              0.5              365305 0.9326743
17  64         256              0.5              613037 0.9311261
18  64         256              0.5              648983 0.9315260
19  64         256              0.5              690506 0.9308874
20  64         256              0.5              700001 0.9300858
21  64         256              0.5              804528 0.9309763
22  64         256              0.8              163687 0.9313089
23  64         256              0.8              365305 0.9308353
24  64         256              0.8              613037 0.9306498
25  64         256              0.8              648983 0.9303083
26  64         256              0.8              690506 0.9310803
27  64         256              0.8              700001 0.9308532
28  64         256              0.8              804528 0.9319451
29  64         512              0.5              163687 0.9320104
30  64         512              0.5              365305 0.9315043
⋮   ⋮          ⋮                ⋮                ⋮      ⋮
321 512         512             0.8              700001 0.9328715
322 512         512             0.8              804528 0.9312978
323 512        1024             0.5              163687 0.9351379
324 512        1024             0.5              365305 0.9328002
325 512        1024             0.5              613037 0.9322004
326 512        1024             0.5              648983 0.9339024
327 512        1024             0.5              690506 0.9334987
328 512        1024             0.5              700001 0.9328646
329 512        1024             0.5              804528 0.9334508
330 512        1024             0.8              163687 0.9346245
331 512        1024             0.8              365305 0.9352362
332 512        1024             0.8              613037 0.9335620
333 512        1024             0.8              648983 0.9325886
334 512        1024             0.8              690506 0.9331844
335 512        1024             0.8              700001 0.9336357
336 512        1024             0.8              804528 0.9323009
337 512        2048             0.5              163687 0.9327658
338 512        2048             0.5              365305 0.9332764
339 512        2048             0.5              613037 0.9327216
340 512        2048             0.5              648983 0.9332425
341 512        2048             0.5              690506 0.9323562
342 512        2048             0.5              700001 0.9314096
343 512        2048             0.5              804528 0.9324363
344 512        2048             0.8              163687 0.9322512
345 512        2048             0.8              365305 0.9325219
346 512        2048             0.8              613037 0.9326843
347 512        2048             0.8              648983 0.9328359
348 512        2048             0.8              690506 0.9329842
349 512        2048             0.8              700001 0.9339849
350 512        2048             0.8              804528 0.9331719
    num_iterations
1    95
2    78
3    94
4   113
5    92
6   102
7   102
8   171
9    86
10  209
11   87
12  200
13   86
14   94
15  109
16  213
17  146
18   95
19   98
20   90
21  150
22   81
23   89
24   96
25  101
26   90
27   82
28  128
29   99
30  169
⋮   ⋮
321  90
322  98
323 105
324  96
325 106
326 108
327  99
328 119
329 116
330 100
331 106
332 117
333 110
334 108
335 107
336 105
337  96
338 163
339 103
340 150
341 154
342 161
343 131
344 175
345  99
346 135
347 109
348 133
349 150
350 117

In [44]:
# Resume por configuración y selecciona por AUC medio entre semillas.
tb_resumen <- tb_nueva[, .(
  AUC_media = mean(AUC),
  AUC_mediana = median(AUC),
  AUC_sd = sd(AUC),
  AUC_min = min(AUC),
  AUC_max = max(AUC),
  iter_media = mean(num_iterations),
  iter_mediana = median(num_iterations)
), by = .(num_leaves, min_data_in_leaf, feature_fraction)]

setorder(tb_resumen, -AUC_media, AUC_sd, num_leaves)
mejor <- tb_resumen[1]

PARAM$out$lgbm$AUC <- mejor$AUC_media
PARAM$out$lgbm$mejores_hiperparametros <- list(
  num_leaves = mejor$num_leaves,
  min_data_in_leaf = mejor$min_data_in_leaf,
  feature_fraction = mejor$feature_fraction,
  num_iterations = as.integer(ceiling(mejor$iter_mediana))
)

PARAM$archivo_grid_resumen <- paste0(
  "grid_resumen_", PARAM$nombre_escenario, ".txt"
)
fwrite(tb_resumen, PARAM$archivo_grid_resumen, sep = "\t")

cat("Mejor configuración del escenario:\n")
print(PARAM$out$lgbm$mejores_hiperparametros)
tb_resumen[1:10]

Mejor configuración del escenario:
$num_leaves
[1] 384

$min_data_in_leaf
[1] 1024

$feature_fraction
[1] 0.8

$num_iterations
[1] 102

   num_leaves min_data_in_leaf feature_fraction AUC_media AUC_mediana
1  384        1024             0.8              0.9336215 0.9333329
2  512        1024             0.8              0.9335903 0.9335620
3  512        1024             0.5              0.9334079 0.9334508
4  256        2048             0.8              0.9330863 0.9331726
5  384        1024             0.5              0.9330786 0.9331450
6  256        1024             0.5              0.9329941 0.9330848
7  128        1024             0.8              0.9329543 0.9328379
8  384        2048             0.8              0.9329192 0.9328359
9  512        2048             0.8              0.9329192 0.9328359
10 256        1024             0.8              0.9328933 0.9330748
   AUC_sd       AUC_min   AUC_max   iter_media iter_mediana
1  0.0010410829 0.9324040 0.9350672 107.14286  102
2  0.0010497911 0.9323009 0.9352362 107.57143  107
3  0.0009460471 0.9322004 0.9351379 107.00000  106
4  0.0005061689 0.9323065 0.9338744 131.00000  133
5  0.0006663141 0.9321050 0.9338405  97.00000   97
6  0.0007801456 0.9320222 0.9342044  99.71429  103
7  0.0005105699 0.9323954 0.9338337 111.14286  114
8  0.0005582817 0.9322512 0.9339849 131.14286  133
9  0.0005582817 0.9322512 0.9339849 131.14286  133
10 0.0008612385 0.9319042 0.9339128 106.14286  108

In [45]:
tb_nueva

    num_leaves min_data_in_leaf feature_fraction seed   AUC
1   64          64              0.5              163687 0.9312291
2   64          64              0.5              365305 0.9300417
3   64          64              0.5              613037 0.9305500
4   64          64              0.5              648983 0.9311892
5   64          64              0.5              690506 0.9321534
6   64          64              0.5              700001 0.9299463
7   64          64              0.5              804528 0.9293502
8   64          64              0.8              163687 0.9301974
9   64          64              0.8              365305 0.9295764
10  64          64              0.8              613037 0.9298708
11  64          64              0.8              648983 0.9304842
12  64          64              0.8              690506 0.9302830
13  64          64              0.8              700001 0.9303101
14  64          64              0.8              804528 0.9308503
15  64         256              0.5              163687 0.9314400
16  64         256              0.5              365305 0.9326743
17  64         256              0.5              613037 0.9311261
18  64         256              0.5              648983 0.9315260
19  64         256              0.5              690506 0.9308874
20  64         256              0.5              700001 0.9300858
21  64         256              0.5              804528 0.9309763
22  64         256              0.8              163687 0.9313089
23  64         256              0.8              365305 0.9308353
24  64         256              0.8              613037 0.9306498
25  64         256              0.8              648983 0.9303083
26  64         256              0.8              690506 0.9310803
27  64         256              0.8              700001 0.9308532
28  64         256              0.8              804528 0.9319451
29  64         512              0.5              163687 0.9320104
30  64         512              0.5              365305 0.9315043
⋮   ⋮          ⋮                ⋮                ⋮      ⋮
321 512         512             0.8              700001 0.9328715
322 512         512             0.8              804528 0.9312978
323 512        1024             0.5              163687 0.9351379
324 512        1024             0.5              365305 0.9328002
325 512        1024             0.5              613037 0.9322004
326 512        1024             0.5              648983 0.9339024
327 512        1024             0.5              690506 0.9334987
328 512        1024             0.5              700001 0.9328646
329 512        1024             0.5              804528 0.9334508
330 512        1024             0.8              163687 0.9346245
331 512        1024             0.8              365305 0.9352362
332 512        1024             0.8              613037 0.9335620
333 512        1024             0.8              648983 0.9325886
334 512        1024             0.8              690506 0.9331844
335 512        1024             0.8              700001 0.9336357
336 512        1024             0.8              804528 0.9323009
337 512        2048             0.5              163687 0.9327658
338 512        2048             0.5              365305 0.9332764
339 512        2048             0.5              613037 0.9327216
340 512        2048             0.5              648983 0.9332425
341 512        2048             0.5              690506 0.9323562
342 512        2048             0.5              700001 0.9314096
343 512        2048             0.5              804528 0.9324363
344 512        2048             0.8              163687 0.9322512
345 512        2048             0.8              365305 0.9325219
346 512        2048             0.8              613037 0.9326843
347 512        2048             0.8              648983 0.9328359
348 512        2048             0.8              690506 0.9329842
349 512        2048             0.8              700001 0.9339849
350 512        2048             0.8              804528 0.9331719
    num_iterations
1    95
2    78
3    94
4   113
5    92
6   102
7   102
8   171
9    86
10  209
11   87
12  200
13   86
14   94
15  109
16  213
17  146
18   95
19   98
20   90
21  150
22   81
23   89
24   96
25  101
26   90
27   82
28  128
29   99
30  169
⋮   ⋮
321  90
322  98
323 105
324  96
325 106
326 108
327  99
328 119
329 116
330 100
331 106
332 117
333 110
334 108
335 107
336 105
337  96
338 163
339 103
340 150
341 154
342 161
343 131
344 175
345  99
346 135
347 109
348 133
349 150
350 117

### 9.3.3 Produccion

#### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

##### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización

In [46]:
meses_final_train_base <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107
)

PARAM$trainingstrategy$final_train <- setdiff(
  meses_final_train_base,
  PARAM$meses_excluidos
)

dataset[, fold_final_train :=
  foto_mes %in% PARAM$trainingstrategy$final_train]

dfinal_train <- lgb.Dataset(
  data = data.matrix(
    dataset[fold_final_train == TRUE, campos_buenos, with = FALSE]
  ),
  label = dataset[fold_final_train == TRUE, clase01],
  free_raw_data = TRUE
)

cat("Filas de final training:",
    nrow(dataset[fold_final_train == TRUE]), "\n")

Filas de final training: 851888

##### Final Training Hyperparameters

In [47]:
# uno los parametros fijos y los mejores encontrados de los variables
fijos <- copy(PARAM$lgbm$param_fijos)

# quito lo que optimice en la Bayesian Optimization
fijos$num_iterations <- NULL
fijos$early_stopping_rounds <- NULL

# agrego a los hiperparametros fijos los que encontre con la Bayesian Optimization
param_final <- c(fijos, PARAM$out$lgbm$mejores_hiperparametros)

##### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [48]:
# Producción completa para todas las semillas configuradas.
if (!require("yaml")) install.packages("yaml")
require("yaml")

PARAM$trainingstrategy$future <- c(202109)
PARAM$kaggle$competencia <- "utn-2026-virtual-jr"
PARAM$kaggle$cortes <- seq(1800, 2400, by = 100)

dfuture <- dataset[foto_mes %in% PARAM$trainingstrategy$future]

if (PARAM$subir_kaggle &&
    length(PARAM$semillas) * length(PARAM$kaggle$cortes) > 100L) {
  warning("La corrida requiere más de 100 submits; Kaggle limita los envíos diarios")
}

tb_produccion <- data.table()

for (semilla in PARAM$semillas) {
  cat("\nProducción - escenario", PARAM$nombre_escenario,
      "- semilla", semilla, "\n")

  carpeta_semilla <- file.path(paste0("semilla_", semilla))
  carpeta_kaggle <- file.path(carpeta_semilla, "kaggle")
  dir.create(carpeta_kaggle, recursive = TRUE, showWarnings = FALSE)

  param_semilla <- copy(param_final)
  param_semilla$seed <- semilla

  final_model <- lgb.train(
    data = dfinal_train,
    param = param_semilla,
    verbose = -100
  )

  lgb.save(final_model, file.path(carpeta_semilla, "modelo.txt"))

  tb_importancia <- as.data.table(lgb.importance(final_model))
  fwrite(
    tb_importancia,
    file.path(carpeta_semilla, "importancia.txt"),
    sep = "\t"
  )

  prediccion <- predict(
    final_model,
    data.matrix(dfuture[, campos_buenos, with = FALSE])
  )

  tb_prediccion <- dfuture[, .(numero_de_cliente)]
  tb_prediccion[, prob := prediccion]
  setorder(tb_prediccion, -prob)

  fwrite(
    tb_prediccion,
    file.path(carpeta_semilla, "prediccion.txt"),
    sep = "\t"
  )

  for (envios in PARAM$kaggle$cortes) {
    tb_prediccion[, Predicted := 0L]
    tb_prediccion[seq_len(envios), Predicted := 1L]

    nombre_archivo <- paste0(
      "KA", PARAM$experimento, "_",
      PARAM$nombre_escenario, "_S", semilla, "_", envios, ".csv"
    )
    archivo_kaggle <- file.path(carpeta_kaggle, nombre_archivo)

    fwrite(
      tb_prediccion[, .(numero_de_cliente, Predicted)],
      archivo_kaggle,
      sep = ","
    )

    estado <- "archivo_generado"
    respuesta <- ""

    if (PARAM$subir_kaggle) {
      mensaje <- paste0(
        "exp=", PARAM$experimento,
        " escenario=", PARAM$nombre_escenario,
        " semilla=", semilla,
        " envios=", envios
      )

      respuesta <- tryCatch(
        system2(
          "kaggle",
          args = c(
            "competitions", "submit",
            "-c", PARAM$kaggle$competencia,
            "-f", shQuote(archivo_kaggle),
            "-m", shQuote(mensaje)
          ),
          stdout = TRUE,
          stderr = TRUE
        ),
        error = function(e) paste("ERROR:", conditionMessage(e))
      )

      estado <- paste(respuesta, collapse = " | ")
      cat(estado, "\n")
      Sys.sleep(30)
    }

    tb_produccion <- rbind(
      tb_produccion,
      data.table(
        experimento = PARAM$experimento,
        escenario = PARAM$nombre_escenario,
        semilla = semilla,
        envios = envios,
        archivo = archivo_kaggle,
        estado = estado
      )
    )

    fwrite(
      tb_produccion,
      paste0("produccion_", PARAM$nombre_escenario, ".txt"),
      sep = "\t"
    )
  }

  rm(final_model, prediccion, tb_prediccion, tb_importancia)
  gc(full = TRUE, verbose = FALSE)
}

write_yaml(
  PARAM,
  file = paste0("PARAM_", PARAM$nombre_escenario, ".yml")
)

cat("Producción finalizada para", length(PARAM$semillas), "semillas\n")
tb_produccion

Loading required package: yaml

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 700001
100%|██████████| 355k/355k [00:00<00:00, 779kB/s] | 0 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Warning message in system2("kaggle", args = c("competitions", "submit", "-c", PARAM$kaggle$competencia, :
“running command ''kaggle' competitions submit -c utn-2026-virtual-jr -f 'semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_1900.csv' -m 'exp=9140 escenario=M2_sin_febrero_marzo_2020 semilla=700001 envios=1900' 2>&1' had status 1”

100%|██████████| 355k/355k [00:00<00:00, 812kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission

Warning message in system2("kaggle", args = c("competitions", "submit", "-c", PARAM$kaggle$competencia, :
“running command ''kaggle' competitions submit -c utn-2026-virtual-jr -f 'semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2000.csv' -m 'exp=9140 escenario=M2_sin_febrero_marzo_2020 semilla=700001 envios=2000' 2>&1' had status 1”

100%|██████████| 355k/355k [00:00<00:00, 792kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission

Warning message in system2("kaggle", args = c("competitions", "submit", "-c", PARAM$kaggle$competencia, :
“running command ''kaggle' competitions submit -c utn-2026-virtual-jr -f 'semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2100.csv' -m 'exp=9140 escenario=M2_sin_febrero_marzo_2020 semilla=700001 envios=2100' 2>&1' had status 1”

100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission

Warning message in system2("kaggle", args = c("competitions", "submit", "-c", PARAM$kaggle$competencia, :
“running command ''kaggle' competitions submit -c utn-2026-virtual-jr -f 'semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2200.csv' -m 'exp=9140 escenario=M2_sin_febrero_marzo_2020 semilla=700001 envios=2200' 2>&1' had status 1”

100%|██████████| 355k/355k [00:00<00:00, 815kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission
100%|██████████| 355k/355k [00:00<00:00, 814kB/s] | 99 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 812kB/s] | 98 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 690506
100%|██████████| 355k/355k [00:00<00:00, 809kB/s] | 97 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 815kB/s] | 96 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 686kB/s] | 95 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 742kB/s]  | 94 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 821kB/s] | 93 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 752kB/s] | 92 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 782kB/s] | 91 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 804528
100%|██████████| 355k/355k [00:00<00:00, 801kB/s] | 90 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 847kB/s] | 89 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 88 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 744kB/s] | 87 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 86 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 802kB/s] | 85 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 808kB/s] | 84 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 613037
100%|██████████| 355k/355k [00:00<00:00, 846kB/s] | 83 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 816kB/s] | 82 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 802kB/s] | 81 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 816kB/s] | 80 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 799kB/s] | 79 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 78 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 708kB/s] | 77 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 648983
100%|██████████| 355k/355k [00:00<00:00, 768kB/s] | 76 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 826kB/s] | 75 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 821kB/s] | 74 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 743kB/s] | 73 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 821kB/s] | 72 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 71 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 769kB/s] | 70 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 365305
100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 69 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 808kB/s] | 68 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 765kB/s] | 67 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 828kB/s] | 66 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 824kB/s] | 65 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 716kB/s] | 64 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 810kB/s] | 63 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

Producción - escenario M2_sin_febrero_marzo_2020 - semilla 163687
100%|██████████| 355k/355k [00:00<00:00, 809kB/s] | 62 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 61 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 834kB/s] | 60 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 849kB/s] | 59 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 841kB/s] | 58 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 832kB/s] | 57 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 56 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
Producción finalizada para 7 semillas

   experimento escenario                 semilla envios
1  9140        M2_sin_febrero_marzo_2020 700001  1800
2  9140        M2_sin_febrero_marzo_2020 700001  1900
3  9140        M2_sin_febrero_marzo_2020 700001  2000
4  9140        M2_sin_febrero_marzo_2020 700001  2100
5  9140        M2_sin_febrero_marzo_2020 700001  2200
6  9140        M2_sin_febrero_marzo_2020 700001  2300
7  9140        M2_sin_febrero_marzo_2020 700001  2400
8  9140        M2_sin_febrero_marzo_2020 690506  1800
9  9140        M2_sin_febrero_marzo_2020 690506  1900
10 9140        M2_sin_febrero_marzo_2020 690506  2000
11 9140        M2_sin_febrero_marzo_2020 690506  2100
12 9140        M2_sin_febrero_marzo_2020 690506  2200
13 9140        M2_sin_febrero_marzo_2020 690506  2300
14 9140        M2_sin_febrero_marzo_2020 690506  2400
15 9140        M2_sin_febrero_marzo_2020 804528  1800
16 9140        M2_sin_febrero_marzo_2020 804528  1900
17 9140        M2_sin_febrero_marzo_2020 804528  2000
18 9140        M2_sin_febrero_marzo_2020 804528  2100
19 9140        M2_sin_febrero_marzo_2020 804528  2200
20 9140        M2_sin_febrero_marzo_2020 804528  2300
21 9140        M2_sin_febrero_marzo_2020 804528  2400
22 9140        M2_sin_febrero_marzo_2020 613037  1800
23 9140        M2_sin_febrero_marzo_2020 613037  1900
24 9140        M2_sin_febrero_marzo_2020 613037  2000
25 9140        M2_sin_febrero_marzo_2020 613037  2100
26 9140        M2_sin_febrero_marzo_2020 613037  2200
27 9140        M2_sin_febrero_marzo_2020 613037  2300
28 9140        M2_sin_febrero_marzo_2020 613037  2400
29 9140        M2_sin_febrero_marzo_2020 648983  1800
30 9140        M2_sin_febrero_marzo_2020 648983  1900
31 9140        M2_sin_febrero_marzo_2020 648983  2000
32 9140        M2_sin_febrero_marzo_2020 648983  2100
33 9140        M2_sin_febrero_marzo_2020 648983  2200
34 9140        M2_sin_febrero_marzo_2020 648983  2300
35 9140        M2_sin_febrero_marzo_2020 648983  2400
36 9140        M2_sin_febrero_marzo_2020 365305  1800
37 9140        M2_sin_febrero_marzo_2020 365305  1900
38 9140        M2_sin_febrero_marzo_2020 365305  2000
39 9140        M2_sin_febrero_marzo_2020 365305  2100
40 9140        M2_sin_febrero_marzo_2020 365305  2200
41 9140        M2_sin_febrero_marzo_2020 365305  2300
42 9140        M2_sin_febrero_marzo_2020 365305  2400
43 9140        M2_sin_febrero_marzo_2020 163687  1800
44 9140        M2_sin_febrero_marzo_2020 163687  1900
45 9140        M2_sin_febrero_marzo_2020 163687  2000
46 9140        M2_sin_febrero_marzo_2020 163687  2100
47 9140        M2_sin_febrero_marzo_2020 163687  2200
48 9140        M2_sin_febrero_marzo_2020 163687  2300
49 9140        M2_sin_febrero_marzo_2020 163687  2400
   archivo
1  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_1800.csv
2  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_1900.csv
3  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2000.csv
4  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2100.csv
5  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2200.csv
6  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2300.csv
7  semilla_700001/kaggle/KA9140_M2_sin_febrero_marzo_2020_S700001_2400.csv
8  semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_1800.csv
9  semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_1900.csv
10 semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_2000.csv
11 semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_2100.csv
12 semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_2200.csv
13 semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_2300.csv
14 semilla_690506/kaggle/KA9140_M2_sin_febrero_marzo_2020_S690506_2400.csv
15 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_1800.csv
16 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_1900.csv
17 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_2000.csv
18 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_2100.csv
19 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_2200.csv
20 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_2300.csv
21 semilla_804528/kaggle/KA9140_M2_sin_febrero_marzo_2020_S804528_2400.csv
22 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_1800.csv
23 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_1900.csv
24 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_2000.csv
25 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_2100.csv
26 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_2200.csv
27 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_2300.csv
28 semilla_613037/kaggle/KA9140_M2_sin_febrero_marzo_2020_S613037_2400.csv
29 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_1800.csv
30 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_1900.csv
31 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_2000.csv
32 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_2100.csv
33 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_2200.csv
34 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_2300.csv
35 semilla_648983/kaggle/KA9140_M2_sin_febrero_marzo_2020_S648983_2400.csv
36 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_1800.csv
37 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_1900.csv
38 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_2000.csv
39 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_2100.csv
40 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_2200.csv
41 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_2300.csv
42 semilla_365305/kaggle/KA9140_M2_sin_febrero_marzo_2020_S365305_2400.csv
43 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_1800.csv
44 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_1900.csv
45 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_2000.csv
46 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_2100.csv
47 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_2200.csv
48 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_2300.csv
49 semilla_163687/kaggle/KA9140_M2_sin_febrero_marzo_2020_S163687_2400.csv
   estado
1  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 779kB/s] | 0 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
2  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 812kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission
3  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 792kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission
4  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission
5  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 815kB/s] | 400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission
6  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 814kB/s] | 99 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
7  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 812kB/s] | 98 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
8  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 809kB/s] | 97 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
9  \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 815kB/s] | 96 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
10 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 686kB/s] | 95 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
11 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r 41%|████      | 144k/355k [00:00<00:00, 1.47MB/s]\r100%|██████████| 355k/355k [00:00<00:00, 742kB/s]  | 94 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
12 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 821kB/s] | 93 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
13 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 752kB/s] | 92 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
14 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 782kB/s] | 91 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
15 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 801kB/s] | 90 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
16 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 847kB/s] | 89 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
17 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 88 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
18 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 744kB/s] | 87 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
19 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 86 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
20 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 802kB/s] | 85 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
21 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 808kB/s] | 84 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
22 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 846kB/s] | 83 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
23 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 816kB/s] | 82 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
24 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 802kB/s] | 81 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
25 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 816kB/s] | 80 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
26 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 799kB/s] | 79 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
27 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 78 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
28 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 708kB/s] | 77 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
29 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 768kB/s] | 76 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
30 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 826kB/s] | 75 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
31 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 821kB/s] | 74 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
32 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 743kB/s] | 73 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
33 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 821kB/s] | 72 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
34 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 71 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
35 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 769kB/s] | 70 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
36 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 69 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
37 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 808kB/s] | 68 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
38 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 765kB/s] | 67 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
39 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 828kB/s] | 66 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
40 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 824kB/s] | 65 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
41 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 716kB/s] | 64 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
42 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 810kB/s] | 63 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
43 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 809kB/s] | 62 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
44 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 840kB/s] | 61 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
45 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 834kB/s] | 60 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
46 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 849kB/s] | 59 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
47 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 841kB/s] | 58 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
48 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 832kB/s] | 57 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr
49 \r  0%|          | 0.00/355k [00:00<?, ?B/s]\r100%|██████████| 355k/355k [00:00<00:00, 819kB/s] | 56 submissions remaining today. | Successfully submitted to UTN 2026 virtual jr

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

*Esta etapa se ejecutó automáticamente en la celda de Producción multisemilla anterior.*

In [49]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Thu Sep 10 00:25:31 2026"